version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - REACT_APP_API_URL=http://backend:5000/movies

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: always
