version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_MOVIE_API_URL: http://107.20.183.9:5000/movies
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    restart: always
