name: Backend CI

on:
  push:
    paths:
      - "starter/backend/**"
      - ".github/workflows/backend-ci.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd starter/backend
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd starter/backend
          pytest
