name: Backend Continuous Integration

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd starter/backend
          pip install flake8
          
      - name: Run Linter
        run: |
          cd starter/backend
          flake8 --exclude=__init__.py .

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd starter/backend
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          cd starter/backend
          python -m unittest test_app.py

  build-backend:
    name: Build Backend Docker
    runs-on: ubuntu-latest
    needs: [lint-backend, test-backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          cd starter/backend
          docker build -t backend-ci-test .
