name: Backend CI

on:
  push:
    paths:
      - 'starter/backend/**'
  pull_request:
    paths:
      - 'starter/backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install pipenv
        run: pip install pipenv

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pipenv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install --dev

      - name: Run tests
        run: |
          cd starter/backend
          pipenv run pytest
