name: CD Pipeline

on:
  push:
    branches: [main]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  IMAGE_TAG: ${{ secrets.IMAGE_TAG }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_BACKEND }}:${{ secrets.IMAGE_TAG }} -f ./starter/backend/Dockerfile ./starter/backend
          docker push ${{ secrets.ECR_REPOSITORY_BACKEND }}:${{ secrets.IMAGE_TAG }}

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_FRONTEND }}:${{ secrets.IMAGE_TAG }} -f ./starter/frontend/Dockerfile ./starter/frontend
          docker push ${{ secrets.ECR_REPOSITORY_FRONTEND }}:${{ secrets.IMAGE_TAG }}

      # Optional: Deploy to Kubernetes
      # Uncomment and configure this block if you have a kubeconfig setup
      # - name: Set up kubectl
      #   uses: azure/setup-kubectl@v3
      #   with:
      #     version: 'v1.29.0'

      # - name: Configure kubeconfig
      #   run: |
      #     mkdir -p ~/.kube
      #     echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config

      # - name: Apply Kubernetes manifests
      #   run: kubectl apply -f k8s/
