name: Frontend CD

on:
  push:
    paths:
      - "starter/frontend/**"
      - ".github/workflows/frontend-cd.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Frontend to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd Rep_Movie_Picture_Pipeline/starter
            git pull origin main
            docker-compose up -d --build
